
def get_record_dict(ids, title, start_date, start_time, end_date,
                    end_time, location_text, location_name,
                    location_address, location_city, depart, postal_code,
                    latitude, longitude, online, training, full, kids,
                    event_link, tickets_link, description):
    return {
        'page_id': ids,
        'title': title,
        'start_date': start_date,
        'start_time': start_time,
        'end_date': end_date,
        'end_time': end_time,
        #'location': location,
        'location_text': location_text,
        'location_name': location_name,
        'location_address': location_address,
        'location_city': location_city,
        'depart': depart,
        'postal_code': postal_code,
        'latitude': latitude,
        'longitude': longitude,
        'online': online,
        'training': training,
        'full': full,
        'kids': kids,
        'original_source_link': event_link,
        'ticketing_platform_link': tickets_link,
        'description': description
    }