def get_record_dict(
    ids,
    title,
    start_date,
    start_time,
    end_date,
    end_time,
    full_location,
    location_name,
    address,
    city,
    department,
    zip_code,
    latitude,
    longitude,
    online,
    training,
    sold_out,
    kids,
    event_link,
    tickets_link,
    description,
):
    return {
        "workshop_type": ids,
        "title": title,
        "start_date": start_date.strftime("%Y-%m-%d"),
        "start_time": start_time.strftime("%I:%M %p"),
        "end_date": end_date.strftime("%Y-%m-%d"),
        "end_time": end_time.strftime("%I:%M %p"),
        #'location': location,
        "full_location": full_location,
        "location_name": location_name,
        "address": address,
        "city": city,
        "department": department,
        "zip_code": zip_code,
        "latitude": latitude,
        "longitude": longitude,
        "online": online,
        "training": training,
        "sold_out": sold_out,
        "kids": kids,
        "source_link": event_link,
        "tickets_link": tickets_link,
        "description": description,
    }
